namespace :categories do
  desc 'Refresh lib/arxiv/data/category_abbreviation_to_label_mapping.xml from arxiv.org/category_taxonomy'
  task :update do
    require 'date'
    require 'nokogiri'
    require 'open-uri'

    taxonomy_url = 'https://arxiv.org/category_taxonomy'
    output_path  = File.expand_path '../lib/arxiv/data/category_abbreviation_to_label_mapping.xml', __dir__
    user_agent   = 'arxiv/categories-updater'

    document = Nokogiri::HTML URI.parse(taxonomy_url).open('User-Agent' => user_agent).read

    categories = []
    group      = nil
    document.css('h2.accordion-head, .accordion-body div.columns.divided').each do |node|
      if node.name == 'h2'
        group = node.text.strip
        next
      end

      heading = node.at_css('h4')
      next if heading.nil?

      match = heading.text.strip.gsub(/\s+/, ' ').match(/\A(\S+)\s+\((.+)\)\z/)
      next if match.nil?

      categories << { id: match[1], group: group, name: match[2] }
    end

    builder = Nokogiri::XML::Builder.new(encoding: 'UTF-8') do |xml|
      xml.comment(" Generated by `rake categories:update` on #{Date.today.iso8601} ")
      xml.comment(" Source: #{taxonomy_url} ")
      xml.comment(" #{categories.length} categories ")
      xml.categories do
        categories.each do |entry|
          xml.category(id: entry[:id], description: "#{entry[:group]} - #{entry[:name]}")
        end
      end
    end

    File.write output_path, builder.to_xml

    puts "wrote #{categories.length} categories to #{output_path}"
  end
end
